"""Add is_admin and is_approved to User

Revision ID: 6e0aabc0268d
Revises:
Create Date: 2025-08-12 21:12:47.446491

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e0aabc0268d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_admin", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("is_approved", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_approved")
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
