"""Admin is now separated

Revision ID: d19e36148b7a
Revises: 6e0aabc0268d
Create Date: 2025-08-12 21:36:26.389100

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d19e36148b7a"
down_revision = "6e0aabc0268d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=180), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_admin_username"), ["username"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_username"))
        batch_op.drop_index(batch_op.f("ix_admin_email"))

    op.drop_table("admin")
    # ### end Alembic commands ###
